//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Policlinic.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientDiagnosis
    {
        public int IdPatientDiagnosis { get; set; }
        public int IdPatient { get; set; }
        public int IdDiagnosis { get; set; }
    
        public virtual Diagnosis Diagnosis { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
