//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Policlinic.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_DepartmentPatient
    {
        public string ФИО_Пациента { get; set; }
        public string Название_услуги { get; set; }
        public string ФИО_Сотрудника { get; set; }
        public string Название_отделения { get; set; }
    }
}
