//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Policlinic.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_MedicalServiceMart
    {
        public string ФИО_Пациента { get; set; }
        public string Название_услуги { get; set; }
        public decimal Цена_услуги { get; set; }
        public System.DateTime Дата_оказания { get; set; }
        public int Продолжительность { get; set; }
    }
}
